version: 2
jobs:
  build:
     docker:
         - image: node:9.5.0
    steps:
      - checkout
      - run:
          name: Install
          command: npm i
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm test