version: 2
machine:
  node:
    version: 9.5.0
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm test